### ISSUE TITLE
Latest commit on keep-session.lua forces mpv to play first video on playlist.

### ISSUE THREAD

**Issue by abhirup7** [CogentRedTester/mpv-scripts#1] opened 2020-04-19 12:51 UTC
Even from starting in file manager if I choose video 20 mpv starts video 1.
Also somehow the script is not being automatically loaded even after adding this line
scripts-opts-append=keep_session-auto_load=yes
 in mpv.conf.
It was working but somehow broke after update.
After reverting to the past .lua without the latest commit the problem with the first video in playlist being  forced to play is solved but mpv still doesn't load automatically so I don't know why if it's a problem with my mpv or with the script.

**Comment by CogentRedTester** [comment] 2020-04-19 12:53
I can't replicate this, so I need a little more information. Could you post both your copy of keep-session.lua, and your mpv.conf file?

**Comment by abhirup7** [comment] 2020-04-19 13:34
save-position-on-quit
scripts-opts-append=keep_session-auto_load=yes
just these 2 lines on mpv.conf and keep-session latest commit casues this issue on my Linux system.
Also using the keep-session.lua file from reddit (past file) makes things go back to normal.
Would just like to add something like save-position-on-quit to this script. Anyway this could be done? mpv starts from 00.00 timestamp of video unless I open video from file manager then it continues from where I left.(the feature I was talking about)

**Comment by CogentRedTester** [comment] 2020-04-19 13:37
how are you opening mpv normally? When you try to have the script activate?

**Comment by abhirup7** [comment] 2020-04-19 13:41
Just clicking mpv icon on dock.

**Comment by CogentRedTester** [comment] 2020-04-19 13:42
I'm not sure, but try adding idle=once to mpv.conf. Also try that with the latest version of the script.

**Comment by abhirup7** [comment] 2020-04-19 13:48
No change. For you does it starts from where you left ?

**Comment by CogentRedTester** [comment] 2020-04-19 13:49
Yes, it works perfectly for me, which is why I'm not just immediately reverting. I made quite a few very useful bug fixes between these versions, and I don't want to give them up until I know why it's not working for you.

**Comment by CogentRedTester** [comment] 2020-04-19 13:54
If you run mpv with the option --msg-level=keep_session='debug' then you can see debug messages from the script.

Pasting them here might be helpful to me figuring out what's going on.
You'd want to run mpv from the terminal for this

**Comment by abhirup7** [comment] 2020-04-19 14:00
![Screenshot from 2020-04-19 19-30-14](https://user-images.githubusercontent.com/44670968/79689722-41348680-8274-11ea-99b7-8f282e23a08a.png)

**Comment by CogentRedTester** [comment] 2020-04-19 14:02
The problem is that you've mis-spelt the config option, it's not scripts-opts-append, it's **script**-opts-append

**Comment by abhirup7** [comment] 2020-04-19 14:12
Yeah yeah I saw that. The latest commit still starts the first video of the playlist. That's why i had deleted this line in the first place and while wrting it again must have used scripts because of the folder name scripts foolishly.
But undoing the latest commit and just using
 if o.maintain_pos and previous_playlist_pos ~= 1 then
works well. Video starts from where I left off.

**Comment by CogentRedTester** [comment] 2020-04-19 14:14
Are you sure that undoing that line is the cause? Because that line is what fixes it for me. What it does is prevent the current file from being reloaded, which wipes the previously saved position. This only seems to happen on playlist entries after the first one.

**Comment by abhirup7** [comment] 2020-04-19 14:15
Wow the video continued where I left off once and now it's back to starting at 00:00.
Something is messing up the good confg I don't understand.

**Comment by CogentRedTester** [comment] 2020-04-19 14:16
Remember that when you change the script/config files mpv doesn't get updated until it restarts. You need to do two mpv restarts to see the fixed results, the first restart to save the session properly, the 2nd to load it.

**Comment by CogentRedTester** [comment] 2020-04-19 14:17
If you could upgrade to the latest version of the script and send me another screenshot of the terminal output that would be great.

**Comment by abhirup7** [comment] 2020-04-19 14:21
mpv git-2020-04-03-f9cc29e Copyright © 2000-2020 mpv/MPlayer/mplayer2 projects
 built on Sat Apr  4 00:21:24 UTC 2020
FFmpeg library versions:
   libavutil       56.42.102
   libavcodec      58.77.101
   libavformat     58.42.100
   libswscale      5.6.101
   libavfilter     7.77.101
   libswresample   3.6.100
FFmpeg version: git-2020-04-03-a6e56d1

Usage:   mpv [options] [url|path/]filename

Basic options:
 --start=<time>    seek to given (percent, seconds, or hh:mm:ss) position
 --no-audio        do not play sound
 --no-video        do not play video
 --fs              fullscreen playback
 --sub-file=<file> specify subtitle file to use
 --playlist=<file> specify playlist file

 --list-options    list all mpv options
 --h=<string>      print options which contain the given string in their name
No error just this stuff.
The latest commit forces mpv to play the first video instead of anything I choose from the playlist but it starts from the position I leave the first video in.
 
I think the one time time it worked perfectly I had undone the latest commit and somehow for one time the chosen video pkayed at left timestamp.

**Comment by CogentRedTester** [comment] 2020-04-19 14:23
It probably showed this because the last session was empty. Try opening a playlist like last time, quitting, then trying again.

**Comment by abhirup7** [comment] 2020-04-19 14:28
mpv just won't start from terminal anymore.

**Comment by CogentRedTester** [comment] 2020-04-19 14:29
What's it saying?

**Comment by CogentRedTester** [comment] 2020-04-19 14:29
Did you have --idle in your config file last time? Try adding that to the command line

**Comment by abhirup7** [comment] 2020-04-19 14:40
![Screenshot from 2020-04-19 20 05 45](https://user-images.githubusercontent.com/44670968/79690705-6aa3e100-8279-11ea-9731-d20903db7a10.png)


Okay i figured out the problem. Removing autload.lua makes keep-session.lua work perfectly. Mpv starts from where i left off and plays correct video from file. But obviously now there's no autmatic playlist and I can't choose next or previous video from mpv.

**Comment by abhirup7** [comment] 2020-04-19 14:41
![Screenshot from 2020-04-19 20 10 50](https://user-images.githubusercontent.com/44670968/79690794-e43bcf00-8279-11ea-8488-fa44b89e9650.png)

**Comment by CogentRedTester** [comment] 2020-04-19 14:44
Yes, autoload.lua would probably break this script. If you like I have a modified autoload.lua that only activates when you use the keybind (ctrl+f8). It's in my main repository.

So to confirm the resume position is working for all files? If so I'll close this issue.

**Closed** 2020-04-19 14:44 UTC
Labels: bug

**Comment by vitormathews** [comment] 2022-12-14 17:35
Is there still no way to use the keep the default autoload behavior together with keep-session?

**Comment by CogentRedTester** [comment] 2023-01-17 11:28
> Is there still no way to use the keep the default autoload behavior together with keep-session?

What exactly do you want to happen? Explain what you want the behaviour to be when you open a file. and what the current behaviour is.
